{% set name = "PyCRS" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6fd88d5b6b1bcd4615c0f9867eab8a8285537119a75d6ead19191b76a0e02c1 

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pycrs
    - pycrs.elements
    - pycrs.load
    - pycrs.parse
    - pycrs.utils

about:
  home: https://github.com/karimbahgat/PyCRS
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'GIS package for reading, writing, and converting between CRS formats.'
  description: |
    PyCRS is a pure Python GIS package for reading, writing, and converting between various common coordinate reference system (CRS) string and data source formats.
  doc_url: https://github.com/karimbahgat/PyCRS
  dev_url: https://github.com/karimbahgat/PyCRS

extra:
  recipe-maintainers:
    - snowman2
    - djhoese
