travis:
  secure:
    BINSTAR_TOKEN: BphJkSvGWfiCB74SL4Z7zdjbQ4wRNMhBHcFzAJsGwAdwGCIBr5YSd3atV+bCQkNvyN/+amO8bWAo2ydKKNV9C6Mv8wPX3Q+3ecRJfG4kedFAG/PQ0kCXfRml+QIY82T5vOJtn/bg4Sek5/5zgN9IUGIeooPeyulyVRHnINltSAYYsolC0IhiAVTeKfFOh3A1cW5QVYkqn+ECkgh3JMrLDWBQj8kHxr/j3vv0NEEMLhmD3di68S5d+cVzptLm4UICVxyS2lmsxF8FK1o44w6rFPw52d9yZ9+aMcXr5BYlhMyqVEoHXmDTEc68FNTefSB8zaa1pbIcFGjI71fEoCFfx1b6ulkS1Bs1rgKrlp1QNLeH/zsoGJnnDSEaBIC5bxyCw8hx1Tu2yt4wCLQDbA/nPFeeF3MKnMYEJxCPNeI3a/q6HXBPGxXx6gFaeReZ2+j7puL/K13veO58yRMEOXT9SQBQBZ8IvgtWUekwgtAsAJO0GFjUand29N4CpEGJxKd2FNKxRihwh0dWqcf9RLIX1C6ygYL7F+N+xfkMbVTszCc9u+XXk0vac0C6yY4KbTUYd9k2XK6clLWv+IUyc82siDUzfjxoUSZIUZ8B0Fq7F8S8fsdobXAPNvcxk0ZDNwGIWj+/lTnzMLR0Fp3k7KMsDyjxTQaF5UjoMzj54Wlz7EY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
